// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9N98AxzMlqMVGaJbQjQXMuq2vk45SnE',
    appId: '1:945631862263:web:3dc143db3c77ed2155a2f2',
    messagingSenderId: '945631862263',
    projectId: 'auth-bloc-b52f4',
    authDomain: 'auth-bloc-b52f4.firebaseapp.com',
    storageBucket: 'auth-bloc-b52f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC31JzzTJdEKb9cDYJSCn6z90cNtAyiTYI',
    appId: '1:945631862263:android:611c3bb9a55928d155a2f2',
    messagingSenderId: '945631862263',
    projectId: 'auth-bloc-b52f4',
    storageBucket: 'auth-bloc-b52f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-MMRixWhLl-nDcH0SpEORyKSYYgRTiRo',
    appId: '1:945631862263:ios:6bca398897e785af55a2f2',
    messagingSenderId: '945631862263',
    projectId: 'auth-bloc-b52f4',
    storageBucket: 'auth-bloc-b52f4.appspot.com',
    iosClientId: '945631862263-slf05d6h5ooigfkg2tu9t8dfgmge41ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-MMRixWhLl-nDcH0SpEORyKSYYgRTiRo',
    appId: '1:945631862263:ios:ea901f3ede1b13e655a2f2',
    messagingSenderId: '945631862263',
    projectId: 'auth-bloc-b52f4',
    storageBucket: 'auth-bloc-b52f4.appspot.com',
    iosClientId: '945631862263-ptkqrbdii8q61hnv02qurmcp0j4oiet2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc.RunnerTests',
  );
}
