name: fb_auth_bloc
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.1
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  flutter_bloc: ^8.1.3
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

